# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84baf78bbc9ea65192bc11e1f7b19fb091942da0a8b0a5149c4220712e53554d1a56736f6ed8b2d633194392d217bdbfe90f18833eeefd066e9c792e3eab3822

test:
  secret_key_base: 17bfa8a5c62816943d458f82572ef4031d303a5072d7164071957f4955e3cfec944fbbe9a905f53652c745f3b2119561834fce9b550d74e8364b45b86081bc5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
